#%RAML 1.0
title: br-order-sys-api

/brorders:
  get:
    queryParameters: 
      orderid:
        required: true 
    responses:
        200:
          body: 
                application/json:
  post:
    body: 
      application/json:
              example:
                          {
                  "message": {
                    "status": "success",
                    "errorMess": "",
                    "errorCode": ""
                  },
                  "order": {
                    "orderNo": "7",
                    "items": [
                      {
                        "itemName": "socks",
                        "itemcode": "S1123",
                        "quantity": 2
                      },
                      {
                        "itemName": "PShirt",
                        "itemcode": "PS112",
                        "quantity": 1
                      }
                    ],
          "htsNo": "QY765G",
          "status": "V"
        }
      }
    responses: 
        200:
          body: 
            application/json:
              example:
                {
                  "status":"order posted successfully"
                }
                          